export enum Intent {
    UNKNOWN = "UNKNOWN",
    GREETING = "GREETING",
    CHAT = "CHAT",
    QUESTION = "QUESTION",
    COMMAND = "COMMAND",
    PROGRAMMING = "PROGRAMMING",
    SEARCH = "SEARCH",
    PLANNING = "PLANNING",
    CREATION = "CREATION",
    SUMMARY = "SUMMARY",
    TRANSLATION = "TRANSLATION",
    CORRECTION = "CORRECTION"
}
